## Open point cloud and triangle mesh

In [8]:
import numpy as np
import open3d as o3d
print("Load a ply point cloud, print it, and render it")
input_file = "C:/Franz/UCA_M1/Semester_2/Case_studies/data/talus_goat_CA_AC_01_MNHN.ply"
mesh = o3d.io.read_triangle_mesh(input_file) # Read the point cloud
pcd = o3d.io.read_point_cloud(input_file)
mesh.compute_vertex_normals()
o3d.visualization.draw_geometries([pcd],
                                  zoom=0.9412,
#                                   front=[0.0, 0.0, 0.0],
                                  front=[0.4257, -0.2125, -0.8795],
                                  lookat=[2.6172, 2.0475, 1.532],
#                                   lookat=[0.0, 0.0, 0.0],
#                                   up=[0.0, -0.8, 0.2])
                                  up=[-0.0694, -0.9768, 0.2024])

Load a ply point cloud, print it, and render it


In [3]:
o3d.io.read_point_cloud(input_file)

PointCloud with 303279 points.

## Generating new mesh test and save image

In [4]:
# generate some neat n times 3 matrix using a variant of sync function
x = np.linspace(-3, 3, 401)
mesh_x, mesh_y = np.meshgrid(x, x)
z = np.sinc((np.power(mesh_x, 2) + np.power(mesh_y, 2)))
z_norm = (z - z.min()) / (z.max() - z.min())
xyz = np.zeros((np.size(mesh_x), 3))
xyz[:, 0] = np.reshape(mesh_x, -1)
xyz[:, 1] = np.reshape(mesh_y, -1)
xyz[:, 2] = np.reshape(z_norm, -1)
print('xyz')
print(xyz)

# Pass xyz to Open3D.o3d.geometry.PointCloud and visualize
pcd = o3d.geometry.PointCloud()
pcd.points = o3d.utility.Vector3dVector(xyz)
o3d.io.write_point_cloud("test_data/sync.ply", pcd)

# Load saved point cloud and visualize it
pcd_load = o3d.io.read_point_cloud("test_data/sync.ply")
o3d.visualization.draw_geometries([pcd_load])

# convert Open3D.o3d.geometry.PointCloud to numpy array
xyz_load = np.asarray(pcd_load.points)
print('xyz_load')
print(xyz_load)
print(xyz_load.shape)

# save z_norm as an image (change [0,1] range to [0,255] range with uint8 type)
img = o3d.geometry.Image((z_norm * 255).astype(np.uint8))
o3d.io.write_image("test_data/sync.png", img)
o3d.visualization.draw_geometries([img])

xyz
[[-3.         -3.          0.17846472]
 [-2.985      -3.          0.17440115]
 [-2.97       -3.          0.17063709]
 ...
 [ 2.97        3.          0.17063709]
 [ 2.985       3.          0.17440115]
 [ 3.          3.          0.17846472]]
xyz_load
[[-3.         -3.          0.17846472]
 [-2.985      -3.          0.17440115]
 [-2.97       -3.          0.17063709]
 ...
 [ 2.97        3.          0.17063709]
 [ 2.985       3.          0.17440115]
 [ 3.          3.          0.17846472]]
(160801, 3)


In [7]:
# Load saved point cloud and visualize it
pcd_load = pcd
o3d.visualization.draw_geometries([pcd_load])

# convert Open3D.o3d.geometry.PointCloud to numpy array
xyz_load = np.asarray(pcd_load.points)
print('xyz_load')
print(xyz_load)
print(xyz_load.shape)

xyz_load
[[ -6.68406677   1.37709808 -10.08659935]
 [ -6.6599865    1.37709808 -10.10533333]
 [ -7.36937904   1.37709808  -8.78660011]
 ...
 [  4.55410004   3.22867584  -1.13394165]
 [  4.70747757   3.08411026  -1.02860641]
 [  4.64929199   3.30615044  -0.97562218]]
(303279, 3)


In [9]:
z = xyz_load[:,2]
z_norm = (z - z.min()) / (z.max() - z.min())

In [10]:
import cv2
# Load an color image in grayscale
img = cv2.imread('DepthCapture_2021-02-24-22-29-56.png',0)
cv2.imshow('image',img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [11]:
img

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=uint8)

In [12]:
# save z_norm as an image (change [0,1] range to [0,255] range with uint8 type)
img = o3d.geometry.Image((z_norm * 255).astype(np.uint8))
o3d.io.write_image("test_data/sync.png", img)
o3d.visualization.draw_geometries([img])

[Open3D WARNING] Write PNG failed: image has no data.


In [7]:
def custom_draw_geometry_with_rotation(pcd):

    def rotate_view(vis):
        ctr = vis.get_view_control()
        ctr.rotate(1.0, 0.0)
        return False

    o3d.visualization.draw_geometries_with_animation_callback([pcd],
                                                              rotate_view)

## New function frontal rotation

In [21]:
def custom_draw_geometry_with_rotation(pcd):

    def rotate_view(vis):
        ctr = vis.get_view_control()
        ctr.rotate(1.0, 0.0)
        return False

    o3d.visualization.draw_geometries_with_animation_callback([pcd],
                                                              rotate_view)

In [22]:
custom_draw_geometry_with_rotation(mesh)

## Same function as draw geometries

In [13]:
def custom_draw_geometry(pcd):
    # The following code achieves the same effect as:
    # o3d.visualization.draw_geometries([pcd])
    vis = o3d.visualization.Visualizer()
    vis.create_window()
    vis.add_geometry(pcd)
    vis.run()
    vis.destroy_window()

In [14]:
custom_draw_geometry(mesh)

In [15]:
def custom_draw_geometry_with_custom_fov(pcd, fov_step):
    vis = o3d.visualization.Visualizer()
    vis.create_window()
    vis.add_geometry(pcd)
    ctr = vis.get_view_control()
    print("Field of view (before changing) %.2f" % ctr.get_field_of_view())
    ctr.change_field_of_view(step=fov_step)
    print("Field of view (after changing) %.2f" % ctr.get_field_of_view())
    vis.run()
    vis.destroy_window()

In [17]:
custom_draw_geometry_with_custom_fov(pcd, 90.0)

Field of view (before changing) 60.00
Field of view (after changing) 90.00


In [18]:
import matplotlib.pyplot as plt
vis = o3d.visualization.Visualizer()
ctr = vis.get_view_control()
#glb = custom_draw_geometry_with_camera_trajectory
vis.create_window()
vis.add_geometry(mesh)
vis.run()
depth = vis.capture_depth_float_buffer(False)
image = vis.capture_screen_float_buffer(False)
# plt.imsave("test_data/depth/{:05d}.png".format(glb.index),\
#         np.asarray(depth), dpi = 1)
# plt.imsave("test_data/image/{:05d}.png".format(glb.index),\
#         np.asarray(image), dpi = 1)
vis.destroy_window()

In [26]:
o3d.visualization.draw_geometries([mesh],
                                  width=512, height=512, left=20, top=20,
                                  zoom=0.9412,
                                  front=[0.4257, -0.2125, -0.8795],
                                  lookat=[2.6172, 2.0475, 1.532],
                                  up=[-0.0694, -0.9768, 0.2024])

## Settings for 3 faces

In [ ]:
## frontal
{
	"class_name" : "ViewTrajectory",
	"interval" : 29,
	"is_loop" : false,
	"trajectory" : 
	[
		{
			"boundingbox_max" : [ 11.244466781616211, 13.512592315673828, 9.9423732757568359 ],
			"boundingbox_min" : [ -9.8325786590576172, -10.730168342590332, -16.346038818359375 ],
			"field_of_view" : 60.0,
			"front" : [ -0.21804549937163129, -0.75319770061983815, -0.62060404767030375 ],
			"lookat" : [ -0.083235890571024249, 5.3312632222438845, -1.0216309515127211 ],
			"up" : [ -0.032123132940909301, -0.63002126999070462, 0.77591320628621896 ],
			"zoom" : 0.94120000000000004
		}
	],
	"version_major" : 1,
	"version_minor" : 0
}

In [ ]:
{
	"class_name" : "ViewTrajectory",
	"interval" : 29,
	"is_loop" : false,
	"trajectory" : 
	[
		{
			"boundingbox_max" : [ 11.244466781616211, 13.512592315673828, 9.9423732757568359 ],
			"boundingbox_min" : [ -9.8325786590576172, -10.730168342590332, -16.346038818359375 ],
			"field_of_view" : 60.0,
			"front" : [ 0.070878400231908847, -0.75882955451385359, -0.64742100643775224 ],
			"lookat" : [ -0.95480318425883659, 5.4455189331947995, -1.0179497201169783 ],
			"up" : [ 0.030612680558826724, -0.64709286128075716, 0.76179635905436438 ],
			"zoom" : 0.94120000000000004
		}
	],
	"version_major" : 1,
	"version_minor" : 0
}

In [ ]:
{
	"class_name" : "ViewTrajectory",
	"interval" : 29,
	"is_loop" : false,
	"trajectory" : 
	[
		{
			"boundingbox_max" : [ 11.244466781616211, 13.512592315673828, 9.9423732757568359 ],
			"boundingbox_min" : [ -9.8325786590576172, -10.730168342590332, -16.346038818359375 ],
			"field_of_view" : 60.0,
			"front" : [ -0.99831913265793937, 0.035955670024447613, -0.045454363511028044 ],
			"lookat" : [ -0.88091834800516555, 2.562232313308348, -1.0601555487524728 ],
			"up" : [ -0.057837826509292929, -0.66816787085058726, 0.74175904590889485 ],
			"zoom" : 0.94120000000000004
		}
	],
	"version_major" : 1,
	"version_minor" : 0
}

## Function with camera trajectory

In [38]:
def custom_draw_geometry_with_camera_trajectory(pcd):
    custom_draw_geometry_with_camera_trajectory.index = -1
    custom_draw_geometry_with_camera_trajectory.trajectory =\
            o3d.io.read_pinhole_camera_trajectory(
                    "../../test_data/camera_trajectory.json")
    custom_draw_geometry_with_camera_trajectory.vis = o3d.visualization.Visualizer(
    )
    if not os.path.exists("../../test_data/image/"):
        os.makedirs("../../test_data/image/")
    if not os.path.exists("../../test_data/depth/"):
        os.makedirs("../../test_data/depth/")

    def move_forward(vis):
        # This function is called within the o3d.visualization.Visualizer::run() loop
        # The run loop calls the function, then re-render
        # So the sequence in this function is to:
        # 1. Capture frame
        # 2. index++, check ending criteria
        # 3. Set camera
        # 4. (Re-render)
        ctr = vis.get_view_control()
        glb = custom_draw_geometry_with_camera_trajectory
        if glb.index >= 0:
            print("Capture image {:05d}".format(glb.index))
            depth = vis.capture_depth_float_buffer(False)
            image = vis.capture_screen_float_buffer(False)
            plt.imsave("../../test_data/depth/{:05d}.png".format(glb.index),\
                    np.asarray(depth), dpi = 1)
            plt.imsave("../../test_data/image/{:05d}.png".format(glb.index),\
                    np.asarray(image), dpi = 1)
            #vis.capture_depth_image("depth/{:05d}.png".format(glb.index), False)
            #vis.capture_screen_image("image/{:05d}.png".format(glb.index), False)
        glb.index = glb.index + 1
        if glb.index < len(glb.trajectory.parameters):
            ctr.convert_from_pinhole_camera_parameters(
                glb.trajectory.parameters[glb.index])
        else:
            custom_draw_geometry_with_camera_trajectory.vis.\
                    register_animation_callback(None)
        return False

    vis = custom_draw_geometry_with_camera_trajectory.vis
    vis.create_window()
    vis.add_geometry(pcd)
    vis.get_render_option().load_from_json("../../test_data/renderoption.json")
    vis.register_animation_callback(move_forward)
    vis.run()
    vis.destroy_window()